library(devtools)

use_r("Trapezoid")
use_r("Simpson")

load_all()
check()
use_mit_license()
document()
check()
install()
use_testthat()
use_test("Trapezoid")
use_test("Simpson")
library(testthat)
load_all()
test()
document()
load_all()
use_readme_rmd()
library(integrateIt)
f <- function(x) {sin(x)}
simpson_fun(a = 0, b = 10, d = 5, f)
trapezoid_fun(a = 0, b = 10, d = 5, f)
build_readme()
check()
install()
rename_files("Trapezoid", "trapezoid_fun")
rename_files("Simpson", "simpson_fun")
document()
load_all()
check()
install()
use_r("Trapezoid")
f(x)
f(3)
library(methods)
use_r("integrateIt-package")
use_r("Simpson")
use_r("intigrateIt")
rename_files("intigrateIt", "integrateIt")
use_r("print")
use_r("getResult")
use_r("getX")
use_r("getY")
rename_files("getX", "getW")

document()
load_all()
check()
install()

integrateIt("Simpson", 0, 10, 5, sin)
integrateIt("Trapezoid", 0, 10, 5, sin)
print("Simpson", 0, 10, 5, sin)
print("Trapezoid", 0, 10, 5, sin)
integrateIt("Trapezoi", 0, 10, 5, sin)
print("Simpso", 0, 10, 5, sin)
simpson_fun(0, 10, 5, sin)

